version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: blog_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - blog_network

  # Django Backend
  backend:
    build: ./backend
    container_name: blog_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - blog_network
    command: bash -c "python manage.py migrate && python manage.py generate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  # Vite Frontend
  frontend:
    build: ./frontend
    container_name: blog_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://0.0.0.0:8000/api
    depends_on:
     - backend
    networks:
      - blog_network
    command: yarn dev --host 0.0.0.0

volumes:
  db_data:

networks:
  blog_network:
    driver: bridge